import os
WORK_PATH = os.getcwd()
os.system("rm Data/Output/*.txt")
os.system("rm Data/Effects/*.txt")
os.system("rm Data/Hybrid/*.txt")
os.system("rm Data/LogFiles/*.log")
os.system("rm Data/ModelData/*.y")
os.system("rm Data/ModelData/*.xt")
os.system("rm Data/ModelPredictions/*.txt")
os.system("rm Data/PreProcessed/*.txt")
os.system("rm Data/PreProcessed/*.x")
os.system("rm Data/PreProcessed/*.libfm")
